function montarSVGString() {
    salvarCaminhoAtivo();
    if(camadas[camadaAtiva]) camadas[camadaAtiva].livreHTML=livreLayer.innerHTML;
    const W=workSurface.offsetWidth,H=workSurface.offsetHeight;
    let defsHTML='', contentHTML='';
    const totalCamadas=camadas.length;
    const fotoPos=(fotoOrdem<0||fotoOrdem>=totalCamadas)?totalCamadas:fotoOrdem;
    function exportarCamada(cam){ if(!cam.visivel)return; if(cam.livreHTML){const tmpSVG=document.createElementNS(NS,'svg');tmpSVG.innerHTML=cam.livreHTML;[...tmpSVG.children].forEach(child=>{if(child.tagName.toLowerCase()==='defs')defsHTML+=child.innerHTML;else contentHTML+=child.outerHTML;});} cam.caminhos.forEach(c=>{const d=buildPathD(c.pontos,c.fechado);if(!d)return;const path=document.createElementNS(NS,'path');path.setAttribute('d',d);aplicarEstiloPath(path,c,cam.opacidade);contentHTML+=path.outerHTML;}); }
    for(let i=totalCamadas-1;i>=fotoPos;i--) exportarCamada(camadas[i]);
    if(camadaFoto.visivel&&camadaFoto.svgHTML){ contentHTML+=`<g opacity="${camadaFoto.opacidade}">${camadaFoto.svgHTML}</g>`; }
    for(let i=fotoPos-1;i>=0;i--) exportarCamada(camadas[i]);
    const texLayer=document.getElementById('texto-layer');
    [...texLayer.children].forEach(child=>{if(child.tagName.toLowerCase()==='defs')defsHTML+=child.innerHTML;else contentHTML+=child.outerHTML;});
    const defsTag=defsHTML?`<defs>${defsHTML}</defs>`:'';
    return `<svg viewBox="0 0 ${W} ${H}" xmlns="http://www.w3.org/2000/svg">${defsTag}${contentHTML}</svg>`;
}
function baixarSVG(){ fecharModalSalvar(); const s=montarSVGString(); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([s],{type:'image/svg+xml'})); a.download='tracemaster.svg'; a.click(); mostrarNotificacao('✅ SVG exportado!'); }
function baixarPDF(){ fecharModalSalvar(); const svgStr=montarSVGString(); const W=workSurface.offsetWidth,H=workSurface.offsetHeight; const blob=new Blob([svgStr],{type:'image/svg+xml'}); const url=URL.createObjectURL(blob); const img=new Image(); img.onload=()=>{const c=document.createElement('canvas');c.width=W;c.height=H;const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,W,H);ctx.drawImage(img,0,0,W,H);URL.revokeObjectURL(url);const {jsPDF}=window.jspdf;const pdf=new jsPDF({orientation:W>H?'landscape':'portrait',unit:'px',format:[W,H]});pdf.addImage(c.toDataURL('image/png'),'PNG',0,0,W,H);pdf.save('tracemaster.pdf');mostrarNotificacao('✅ PDF exportado!');}; img.src=url; }
function salvarProjeto(){ salvarCaminhoAtivo(); if(camadas[camadaAtiva])camadas[camadaAtiva].livreHTML=livreLayer.innerHTML; const nome=prompt('Nome do projeto:','Projeto '+new Date().toLocaleDateString('pt-BR')); if(!nome)return; const projeto={nome,versao:'2.0',data:new Date().toLocaleString('pt-BR'),camadas,camadaFoto,textoHTML:document.getElementById('texto-layer').innerHTML,workW:workSurface.offsetWidth,workH:workSurface.offsetHeight,modoInfinito,gradeAtiva,gradeTamanho,rotacao}; const lista=JSON.parse(localStorage.getItem('tm_projetos')||'[]'); const existIdx=lista.findIndex(p=>p.nome===nome); if(existIdx>=0)lista[existIdx]=projeto; else lista.push(projeto); localStorage.setItem('tm_projetos',JSON.stringify(lista)); fecharModalSalvar(); setTimeout(()=>voltarInicio(),300); }
function abrirProjetos(){ const listaEl=document.getElementById('lista-projetos'); const lista=JSON.parse(localStorage.getItem('tm_projetos')||'[]'); if(lista.length===0){listaEl.style.display='block';listaEl.innerHTML='<p style="color:#888;font-size:12px;text-align:center;">Nenhum projeto salvo ainda.</p>';return;} listaEl.style.display='block'; listaEl.innerHTML=lista.map((p,i)=>`<div style="background:#2a2a2a;border-radius:8px;padding:8px 10px;margin-bottom:6px;display:flex;align-items:center;gap:8px;"><div style="flex:1;"><div style="font-size:12px;font-weight:bold;">${p.nome}</div><div style="font-size:10px;color:#666;">${p.data}</div></div><button onclick="carregarProjeto(${i})" style="background:#2980b9;color:white;border:none;padding:5px 10px;border-radius:5px;font-size:11px;font-weight:bold;">ABRIR</button><button onclick="deletarProjeto(${i})" style="background:#7b2020;color:white;border:none;padding:5px 8px;border-radius:5px;font-size:11px;">✕</button></div>`).join(''); }
function carregarProjeto(idx){ const lista=JSON.parse(localStorage.getItem('tm_projetos')||'[]'); const p=lista[idx]; if(!p)return; camadas=p.camadas; camadaFoto=p.camadaFoto; fotoOrdem=(p.fotoOrdem!==undefined)?p.fotoOrdem:-1; camadaAtiva=0;caminhoAtivo=-1;pontosPen=[];pathFechado=false;penLayer.innerHTML=''; workSurface.style.width=p.workW+'px';workSurface.style.height=p.workH+'px'; rotacao=p.rotacao||0; svgArea.innerHTML=camadaFoto.svgHTML||''; document.getElementById('texto-layer').innerHTML=p.textoHTML||''; historico=[];historicoFuturo=[]; _esconderBolinhasDegrade();_esconderBolinhasTxtDg();modoDegrade=false;degradeStart=null;_dgPrevReset(); document.getElementById('btnDegrade').style.background='#e74c3c'; document.getElementById('degrade-preview-layer').innerHTML=''; renderizarTodos();if(painelAberto)renderizarPainel();fecharModalSalvar();document.getElementById('lista-projetos').style.display='none';mostrarNotificacao('✅ "'+p.nome+'" aberto!'); }
function deletarProjeto(idx){ const lista=JSON.parse(localStorage.getItem('tm_projetos')||'[]'); lista.splice(idx,1); localStorage.setItem('tm_projetos',JSON.stringify(lista)); abrirProjetos(); }
function carregarProjetoInicial(idx){ const lista=JSON.parse(localStorage.getItem('tm_projetos')||'[]'); const p=lista[idx]; if(!p)return; camadas=p.camadas; camadaFoto=p.camadaFoto; fotoOrdem=(p.fotoOrdem!==undefined)?p.fotoOrdem:-1; camadaAtiva=0;caminhoAtivo=-1;pontosPen=[];pathFechado=false;penLayer.innerHTML=''; if(p.workW)workSurface.style.width=p.workW+'px'; if(p.workH)workSurface.style.height=p.workH+'px'; rotacao=p.rotacao||0; svgArea.innerHTML=camadaFoto.svgHTML||''; document.getElementById('texto-layer').innerHTML=p.textoHTML||''; historico=[];historicoFuturo=[]; modoInfinito=p.modoInfinito||false; gradeAtiva=p.gradeAtiva||false; gradeTamanho=p.gradeTamanho||20; _esconderBolinhasDegrade();_esconderBolinhasTxtDg();modoDegrade=false;degradeStart=null;_dgPrevReset(); document.getElementById('btnDegrade').style.background='#e74c3c'; document.getElementById('degrade-preview-layer').innerHTML=''; aplicarModoInfinito(modoInfinito); renderizarTodos(); abrirEditor(); }
function deletarProjetoInicial(idx){ const lista=JSON.parse(localStorage.getItem('tm_projetos')||'[]'); lista.splice(idx,1); localStorage.setItem('tm_projetos',JSON.stringify(lista)); renderizarTelaInicial(); }
